.TH PASSPHERA 1 "September 2025" "1.2.0" "User Commands"

.SH NAME
passphera \- strong passwords generator and manager

.SH SYNOPSIS
.B passphera
[\fB\-v\fR|\fB\-\-version\fR]
[\fB\-h\fR|\fB\-\-help\fR]
\fBCOMMAND\fR
[\fIARGS\fR...]

.SH DESCRIPTION
.B passphera
is an offline-first password generator and manager.
It lets you generate strong, consistent passwords based on customizable settings, manage them locally, and optionally synchronize both your vault and generator configuration with the cloud. capabilities.

.SH COMMANDS

.SS Authentication Commands
.TP
.B auth login \-e \fIEMAIL\fR \-p \fIPASSWORD\fR
Login with your email and passowrd
.TP
.B auth logout
Logout from the current session
.TP
.B auth signup \-e \fIEMAIL\fR \-n \fIUSERNAME\fR \-p \fIPASSWORD\fR
Register new user
.TP
.B auth whoami
Display current logged in user

.SS Generator Commands
.TP
.B generator show
Show all generator settings
.TP
.B generator set \fIPROPERTY\fR \fIVALUE\fR
Set generator property (shift, multiplier, key, algorithm, prefix, postfix)
.TP
.B generator reset \fIPROPERTY\fR
Reset a property to its default value
.TP
.B generator set-replacement \fICHARACTER\fR \fIREPLACEMENT\fR
Set character replacement
.TP
.B generator reset-replacement \fICHARACTER\fR
Reset character replacement
.TP
.B generator sync [up|down]
Synchronize generator settings with the cloud

.SS Vault Commands
.TP
.B vault add \-t \fITEXT\fR \-c \fICONTEXT\fR
Generate a new password and optionally save it
.TP
.B vault get \fICONTEXT\fR
Get a saved password by its context and copy it to the clipboard
.TP
.B vault update \fICONTEXT\fR \-t \fITEXT\fR
Update a saved password
.TP
.B vault delete \fICONTEXT\fR
Delete a saved password
.TP
.B vault list
List all saved passwords on the vault
.TP
.B vault flush
Flush the vault and delete all saved passwords
.TP
.B vault sync
Synchronize with cloud storage

.SH OPTIONS
.TP
.BR \-v ", " \-\-version
Show program version
.TP
.BR \-h ", " \-\-help
Show help message

.SH EXAMPLES
.PP
Login to account:
.PP
.nf
.RS
passphera auth login -e user@example.com -p mypassword
.RE
.fi
.PP
Generate and save a password:
.PP
.nf
.RS
passphera vault add -t "master_key" -c "github" or passphera generate -t "master_key" -c "github"
.RE
.fi
.PP
Configure encryption settings:
.PP
.nf
.RS
passphera generator set algorithm playfair
passphera generator set key mysecretkey
passphera generator set shift 5
.RE
.fi
.PP
Retrieve a saved password:
.PP
.nf
.RS
passphera vault get "github"
.RE
.fi

.SH FILES
.TP
.I ~/.config/passphera/config.ini
User configuration file
.TP
.I ~/.local/share/passphera/.vault
The local database

.SH BUGS
Report bugs at: https://github.com/passphera/cli/issues

.SH AUTHOR
Fathi Abdelmalek <passphera@imfathi.com>

.SH COPYRIGHT
Copyright © 2024 Fathi Abdelmalek. Licensed under Apache License 2.0.
